spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${QUERY-DB-ADDRESS}
    username: ${QUERY-DB-HOST}
    password: ${QUERY-DB-PASSWORD}