spring:
  config:
    activate:
      on-profile: dev
  datasource:
    # Command DB
    hikari:
      jdbc-url: jdbc:mysql://${COMMAND-DB-ADDRESS}:3306/member
      username: ${COMMAND-DB-HOST}
      password: ${COMMAND-DB-PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  # Query DB
  query-datasource:
    hikari:
      jdbc-url: jdbc:mysql://${QUERY-DB-ADDRESS}:3306/moaboa
      username: ${QUERY-DB-HOST}
      password: ${QUERY-DB-PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

