spring:
  profiles:
    active: ${profile}
    group:
      local: common, local
      dev: common, dev

---
spring:
  config:
    activate:
      on-profile:
        common
  data:
    redis:
      host: redis-database
      port: 6379
  application:
    name: auth-service
  #  cloud:
  #    zookeeper:
  #      connect-string: localhost:2181
  #      discovery:
  #        enabled: true
  #        root: /services
  #        instance-id: ${spring.application.name}:${server.port}}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLEINT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
        #              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 9000

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    header: Authorization
    expiration: 7200000 #2시간
  refresh:
    header: Refresh-Token
    expiration: 2678400000 #31일

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: "/auth"
