spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
#  cloud:
#    zookeeper:
#      connect-string: localhost:2181
#      discovery:
#        enabled: true
#        root: /services
#        instance-id: ${spring.application.name}:${server.port}}